//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotSpatial.Plugins.MenuBar {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotSpatial.Plugins.MenuBar.MessageStrings", typeof(MessageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 增加图层... 的本地化字符串。
        /// </summary>
        internal static string Add_Layer {
            get {
                return ResourceManager.GetString("Add_Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消选择 的本地化字符串。
        /// </summary>
        internal static string Deselect {
            get {
                return ResourceManager.GetString("Deselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string File_Exit {
            get {
                return ResourceManager.GetString("File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建 的本地化字符串。
        /// </summary>
        internal static string File_New {
            get {
                return ResourceManager.GetString("File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开... 的本地化字符串。
        /// </summary>
        internal static string File_Open {
            get {
                return ResourceManager.GetString("File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印... 的本地化字符串。
        /// </summary>
        internal static string File_Print {
            get {
                return ResourceManager.GetString("File_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置窗口 的本地化字符串。
        /// </summary>
        internal static string File_Reset_Layout {
            get {
                return ResourceManager.GetString("File_Reset_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string File_Save {
            get {
                return ResourceManager.GetString("File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另存为... 的本地化字符串。
        /// </summary>
        internal static string File_SaveAs {
            get {
                return ResourceManager.GetString("File_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clears the current map. The user is prompted to save any changes to the current map project. 的本地化字符串。
        /// </summary>
        internal static string FileNewToolTip {
            get {
                return ResourceManager.GetString("FileNewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clears the current map and shows an ‘Open’ window that allows the user to navigate to a previously saved map. 的本地化字符串。
        /// </summary>
        internal static string FileOpenToolTip {
            get {
                return ResourceManager.GetString("FileOpenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allows the user to save the project. 的本地化字符串。
        /// </summary>
        internal static string FileSaveAsToolTip {
            get {
                return ResourceManager.GetString("FileSaveAsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allows the user to name the file and location where the map is to be saved on their computer. 的本地化字符串。
        /// </summary>
        internal static string FileSaveToolTip {
            get {
                return ResourceManager.GetString("FileSaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常用功能 的本地化字符串。
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 识别 的本地化字符串。
        /// </summary>
        internal static string Identify {
            get {
                return ResourceManager.GetString("Identify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图层 的本地化字符串。
        /// </summary>
        internal static string Layers_Group {
            get {
                return ResourceManager.GetString("Layers_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map Tool 的本地化字符串。
        /// </summary>
        internal static string Map_Tools_Group {
            get {
                return ResourceManager.GetString("Map_Tools_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平移 的本地化字符串。
        /// </summary>
        internal static string Pan {
            get {
                return ResourceManager.GetString("Pan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指针 的本地化字符串。
        /// </summary>
        internal static string Pointer {
            get {
                return ResourceManager.GetString("Pointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除图层 的本地化字符串。
        /// </summary>
        internal static string Remove_Layer {
            get {
                return ResourceManager.GetString("Remove_Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保留图层... 的本地化字符串。
        /// </summary>
        internal static string Save_Layer {
            get {
                return ResourceManager.GetString("Save_Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看 的本地化字符串。
        /// </summary>
        internal static string View_Group {
            get {
                return ResourceManager.GetString("View_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放 的本地化字符串。
        /// </summary>
        internal static string Zoom_Group {
            get {
                return ResourceManager.GetString("Zoom_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放大 的本地化字符串。
        /// </summary>
        internal static string Zoom_In {
            get {
                return ResourceManager.GetString("Zoom_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放大 的本地化字符串。
        /// </summary>
        internal static string Zoom_In_Tooltip {
            get {
                return ResourceManager.GetString("Zoom_In_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一个 的本地化字符串。
        /// </summary>
        internal static string Zoom_Next {
            get {
                return ResourceManager.GetString("Zoom_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一个 的本地化字符串。
        /// </summary>
        internal static string Zoom_Next_Tooltip {
            get {
                return ResourceManager.GetString("Zoom_Next_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩小 的本地化字符串。
        /// </summary>
        internal static string Zoom_Out {
            get {
                return ResourceManager.GetString("Zoom_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩小 的本地化字符串。
        /// </summary>
        internal static string Zoom_Out_Tooltip {
            get {
                return ResourceManager.GetString("Zoom_Out_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前一个 的本地化字符串。
        /// </summary>
        internal static string Zoom_Previous {
            get {
                return ResourceManager.GetString("Zoom_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前一个 的本地化字符串。
        /// </summary>
        internal static string Zoom_Previous_Tooltip {
            get {
                return ResourceManager.GetString("Zoom_Previous_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定位 的本地化字符串。
        /// </summary>
        internal static string Zoom_To_Coordinates {
            get {
                return ResourceManager.GetString("Zoom_To_Coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全图 的本地化字符串。
        /// </summary>
        internal static string Zoom_To_Extents {
            get {
                return ResourceManager.GetString("Zoom_To_Extents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全图 的本地化字符串。
        /// </summary>
        internal static string Zoom_To_Extents_Tooltip {
            get {
                return ResourceManager.GetString("Zoom_To_Extents_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图层 的本地化字符串。
        /// </summary>
        internal static string Zoom_To_Layer {
            get {
                return ResourceManager.GetString("Zoom_To_Layer", resourceCulture);
            }
        }
    }
}
