//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotSpatial.Plugins.WebMap.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotSpatial.Plugins.WebMap.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Bing Aerial Map 的本地化字符串。
        /// </summary>
        internal static string BingAerial {
            get {
                return ResourceManager.GetString("BingAerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bing Hybrid Map 的本地化字符串。
        /// </summary>
        internal static string BingHybrid {
            get {
                return ResourceManager.GetString("BingHybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bing Street Map 的本地化字符串。
        /// </summary>
        internal static string BingRoads {
            get {
                return ResourceManager.GetString("BingRoads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Esri Hydro Base Map 的本地化字符串。
        /// </summary>
        internal static string EsriHydroBaseMap {
            get {
                return ResourceManager.GetString("EsriHydroBaseMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Esri World Hydro Overlay 的本地化字符串。
        /// </summary>
        internal static string EsriWorldHydroBasemap {
            get {
                return ResourceManager.GetString("EsriWorldHydroBasemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Esri World Imagery 的本地化字符串。
        /// </summary>
        internal static string EsriWorldImagery {
            get {
                return ResourceManager.GetString("EsriWorldImagery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Esri World Street Map 的本地化字符串。
        /// </summary>
        internal static string EsriWorldStreetMap {
            get {
                return ResourceManager.GetString("EsriWorldStreetMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Esri World Topo 的本地化字符串。
        /// </summary>
        internal static string EsriWorldTopo {
            get {
                return ResourceManager.GetString("EsriWorldTopo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Google Labels 的本地化字符串。
        /// </summary>
        internal static string GoogleLabels {
            get {
                return ResourceManager.GetString("GoogleLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Google Map 的本地化字符串。
        /// </summary>
        internal static string GoogleMap {
            get {
                return ResourceManager.GetString("GoogleMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Google Satellite 的本地化字符串。
        /// </summary>
        internal static string GoogleSatellite {
            get {
                return ResourceManager.GetString("GoogleSatellite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Google Terrain 的本地化字符串。
        /// </summary>
        internal static string GoogleTerrain {
            get {
                return ResourceManager.GetString("GoogleTerrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Online Basemap 的本地化字符串。
        /// </summary>
        internal static string Legend_Title {
            get {
                return ResourceManager.GetString("Legend_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap nodata {
            get {
                object obj = ResourceManager.GetObject("nodata", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 透明度： 的本地化字符串。
        /// </summary>
        internal static string Opacity_Box_Text {
            get {
                return ResourceManager.GetString("Opacity_Box_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 改变地图的透明度 的本地化字符串。
        /// </summary>
        internal static string Opacity_Box_ToolTip {
            get {
                return ResourceManager.GetString("Opacity_Box_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Street Map 的本地化字符串。
        /// </summary>
        internal static string OpenStreetMap {
            get {
                return ResourceManager.GetString("OpenStreetMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载 的本地化字符串。
        /// </summary>
        internal static string Panel_Name {
            get {
                return ResourceManager.GetString("Panel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change online basemap service. 的本地化字符串。
        /// </summary>
        internal static string Service_Box_ToolTip {
            get {
                return ResourceManager.GetString("Service_Box_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WMS 的本地化字符串。
        /// </summary>
        internal static string WMSMap {
            get {
                return ResourceManager.GetString("WMSMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yahoo Hybrid 的本地化字符串。
        /// </summary>
        internal static string YahooHybrid {
            get {
                return ResourceManager.GetString("YahooHybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yahoo Map 的本地化字符串。
        /// </summary>
        internal static string YahooNormal {
            get {
                return ResourceManager.GetString("YahooNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yahoo Satellite 的本地化字符串。
        /// </summary>
        internal static string YahooSatellite {
            get {
                return ResourceManager.GetString("YahooSatellite", resourceCulture);
            }
        }
    }
}
